POST http://localhost:3001/api/tasks-collections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YzliMDcyMjMyZWM4ZTc1NTEwZTU2NCIsImlhdCI6MTcyNDQ5NDg1NH0.VTCRFd3Lb_vhWv2b_9WTDaz99E0ED2cDQ74FyVzZzks

{
  "name": "test3"
}